---

apiVersion: v1
kind: Service
metadata:
  name: frontend-cip
  namespace: step-2
  labels:
    demo/project: c_ipc
    demo/app: step-2
spec:
  type: NodePort
  selector:
    demo/project: c_ipc
    demo/app: step-2
    demo/module: thermometer-1
    demo/ipctype: client
    demo/ipctopic: distribution-bell
    active: "yes"
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30082
